export const routePaths = {
  home: '/',
  login: '/login',
  register: '/register',
  cart: '/cart',
  profile: '/account/profile',
  purchase: '/account/purchase',
  men: '/men',
  women: '/women',
  hoodies: '/',
  casual: '/',
  products: '/products',
  detail: '/products/:id',
  payment: '/payment',
  notFound: '*',
  orderDetailPath: '/order/:id',
  orderDetail: (id: number | string) => `/order/${id}`,
} as const;
